name: Node.js CI

on:
  push:
    branches: [staging]
  pull_request:
    branches: [main, staging]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: mskelton/setup-yarn@v1
        with:
          ref: ${{ github.head_ref }}
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Linting...
        run: yarn lint
      # - name: Building...
      #   run: yarn build
      - name: Running unit tests...
        run: yarn test
